# Generated by Django 4.2 on 2023-04-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendimento', models.FloatField(max_length=3)),
                ('pontualidade', models.FloatField(max_length=3)),
                ('qualidade', models.FloatField(max_length=3)),
            ],
        ),
    ]
