# Generated by Django 4.2 on 2023-04-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='atendimento',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='pontualidade',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='qualidade',
            field=models.IntegerField(max_length=3),
        ),
    ]
